const GUITAR_CONFIG = {
  NECK_OFFSET: 260,

  STRING_END_Y_OFFSET: 50,
  STRING_START_X_OFFSET: 135,
  STRING_START_Y: 50,
  STRING_WIDTH_PERCENT: 0.2,
  STRINGS: ['A', 'B', 'D', 'E', 'G'],

  TOTAL_WAVES: 20,
  WAVE_HEIGHT: 2,
};

export default GUITAR_CONFIG;
